/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ServiceMetadata } from '../types/service';
import { NavItem } from '../types/navigation';

export const APP_CONFIG = {
  name: 'LingoFlow',
  tagline: 'Multimodal Translation Workspace',
  version: '0.1.0-alpha',
  phase: 'Production Hardening',
  theme: {
    colors: {
      primary: '#5B5FEF',
      secondary: '#22D3EE',
      lightBg: '#F8FAFC',
      primaryText: '#111827',
      secondaryText: '#64748B',
      success: '#10B981',
      darkBg: '#080B14',
      darkCard: '#111827',
      darkPrimary: '#7C83FF',
    },
    fontFamily: {
      sans: 'Inter, system-ui, -apple-system, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
  },
} as const;

export const NAVIGATION_ITEMS: readonly NavItem[] = [
  {
    id: 'home',
    label: 'Home',
    description: 'Overview & 3D Language Solar System',
    iconName: 'Home',
    shortcut: '1',
  },
  {
    id: 'translator',
    label: 'Translator',
    description: 'Translation Cockpit & Intelligence',
    iconName: 'Languages',
    shortcut: '2',
  },
  {
    id: 'search',
    label: 'Web Search',
    description: 'Real-time web-grounded research',
    iconName: 'Globe',
    shortcut: '3',
  },
  {
    id: 'semantic',
    label: 'Semantic Mirror',
    description: 'Meaning Integrity & Meaning Lock',
    iconName: 'Sparkles',
    shortcut: '4',
  },
  {
    id: 'conversation',
    label: 'Conversation',
    description: 'Two-person multilingual split dialogue',
    iconName: 'MessagesSquare',
    shortcut: '5',
  },
  {
    id: 'media',
    label: 'Media & Docs',
    description: 'Image OCR & Document translation',
    iconName: 'FileText',
    shortcut: '6',
  },
  {
    id: 'history',
    label: 'History & Stats',
    description: 'Saved translations & real usage metrics',
    iconName: 'History',
    shortcut: '7',
  },
  {
    id: 'languages',
    label: 'Languages',
    description: 'Language explorer & offline pack manager',
    iconName: 'Globe',
    shortcut: '8',
  },
  {
    id: 'vault',
    label: 'Vault',
    description: 'Google Drive cloud backup folders',
    iconName: 'HardDrive',
    shortcut: '9',
  },
  {
    id: 'settings',
    label: 'Settings',
    description: 'Theme, PWA, and application settings',
    iconName: 'Settings',
    shortcut: '0',
  },
] as const;

export const FUTURE_MODULE_SPECS: readonly ServiceMetadata[] = [
  {
    id: 'storageService',
    name: 'Storage Service',
    category: 'persistence',
    description: 'Local persistent key-value & IndexedDB storage engine for offline-first data, cached lexicons, and user preferences.',
    isOfflineCapable: true,
    phaseScheduled: 'Phase 0 (Foundation)',
    contractDefined: true,
    status: 'ready',
    capabilities: ['KeyValue Store', 'Cache Quotas', 'Offline Persistence', 'IndexDB Adapter'],
  },
  {
    id: 'syncService',
    name: 'Sync Service',
    category: 'persistence',
    description: 'Offline-to-online change tracking, conflict resolution, and background synchronization engine.',
    isOfflineCapable: true,
    phaseScheduled: 'Phase 1',
    contractDefined: true,
    status: 'pending_phase',
    capabilities: ['Delta Sync', 'Offline Queue', 'CRDT Conflict Resolution', 'Network Listener'],
  },
  {
    id: 'translationService',
    name: 'Translation Service',
    category: 'ai',
    description: 'Context-aware multilingual neural translation engine supporting 100+ languages with nuance awareness.',
    isOfflineCapable: false,
    phaseScheduled: 'Phase 1',
    contractDefined: true,
    status: 'pending_phase',
    capabilities: ['Online Neural Translation', 'Language Detection', 'Multi-variant Selection', 'Glossary Injection'],
  },
  {
    id: 'offlineTranslationService',
    name: 'Offline Translation Service',
    category: 'core',
    description: 'Local on-device translation engine executing without internet connection using quantized models.',
    isOfflineCapable: true,
    phaseScheduled: 'Phase 2',
    contractDefined: true,
    status: 'pending_phase',
    capabilities: ['On-Device Inference', 'Offline Model Packs', 'Zero-Latency Translation', 'Local Fallback'],
  },
  {
    id: 'semanticService',
    name: 'Semantic Service',
    category: 'ai',
    description: 'Deep semantic analysis providing Meaning Lock preservation, contextual breakdown, and cultural tone analysis.',
    isOfflineCapable: false,
    phaseScheduled: 'Phase 1',
    contractDefined: true,
    status: 'pending_phase',
    capabilities: ['Semantic Mirror', 'Meaning Lock Guard', 'Tone Analysis', 'Formality Scoring'],
  },
  {
    id: 'speechService',
    name: 'Speech Service',
    category: 'multimodal',
    description: 'Bidirectional speech engine providing real-time audio transcription and natural neural text-to-speech.',
    isOfflineCapable: false,
    phaseScheduled: 'Phase 2',
    contractDefined: true,
    status: 'pending_phase',
    capabilities: ['Voice Dictation', 'Neural Speech Synthesis', 'Accent Adaptation', 'Audio Stream Processing'],
  },
  {
    id: 'ocrService',
    name: 'OCR Service',
    category: 'multimodal',
    description: 'Document and camera visual optical character recognition with layout retention and in-situ translation.',
    isOfflineCapable: false,
    phaseScheduled: 'Phase 2',
    contractDefined: true,
    status: 'pending_phase',
    capabilities: ['Image Text Extraction', 'Bounding Box Detection', 'Document Layout Preservation', 'Multi-script OCR'],
  },
  {
    id: 'googleDriveService',
    name: 'Google Drive Service',
    category: 'cloud',
    description: 'Secure cloud vault integration for cross-device workspace backups, translation memory sync, and document exports.',
    isOfflineCapable: false,
    phaseScheduled: 'Phase 3',
    contractDefined: true,
    status: 'pending_phase',
    capabilities: ['Drive Vault Backups', 'Encrypted Archive Sync', 'Document Exporting', 'OAuth Token Management'],
  },
] as const;
