/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface LanguagePlanetData {
  code: string;
  name: string;
  nativeName: string;
  script: string;
  family: string;
  orbitRadius: number; // 3D orbital distance from LingoFlow Core
  orbitIndex: number;  // 1 to 4
  color: string;
  size: number;
  speed: number;
  initialAngle: number;
  cloudSupported: boolean;
  offlineSupported: boolean;
  textSupported: boolean;
  speechSynthesisSupported: boolean;
  speechRecognitionSupported: boolean;
  ocrSupported: boolean;
  documentSupported: boolean;
  limitations?: string;
  popular: boolean;
  bcp47: string;
  flagGlyph: string;
}

export const SUPPORTED_LANGUAGES: LanguagePlanetData[] = [
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    script: 'Latin',
    family: 'Indo-European (Germanic)',
    orbitRadius: 130,
    orbitIndex: 1,
    color: '#5B5FEF',
    size: 15,
    speed: 0.0006,
    initialAngle: 0,
    cloudSupported: true,
    offlineSupported: true,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: true,
    bcp47: 'en-US',
    flagGlyph: 'EN',
  },
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    script: 'Latin',
    family: 'Indo-European (Romance)',
    orbitRadius: 130,
    orbitIndex: 1,
    color: '#F59E0B',
    size: 14,
    speed: 0.0006,
    initialAngle: (Math.PI * 2) / 4,
    cloudSupported: true,
    offlineSupported: true,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: true,
    bcp47: 'es-ES',
    flagGlyph: 'ES',
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    script: 'Latin',
    family: 'Indo-European (Romance)',
    orbitRadius: 130,
    orbitIndex: 1,
    color: '#3B82F6',
    size: 13,
    speed: 0.0006,
    initialAngle: (Math.PI * 4) / 4,
    cloudSupported: true,
    offlineSupported: true,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: true,
    bcp47: 'fr-FR',
    flagGlyph: 'FR',
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    script: 'Latin',
    family: 'Indo-European (Germanic)',
    orbitRadius: 130,
    orbitIndex: 1,
    color: '#EAB308',
    size: 13,
    speed: 0.0006,
    initialAngle: (Math.PI * 6) / 4,
    cloudSupported: true,
    offlineSupported: true,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: true,
    bcp47: 'de-DE',
    flagGlyph: 'DE',
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    script: 'Devanagari',
    family: 'Indo-European (Indo-Aryan)',
    orbitRadius: 185,
    orbitIndex: 2,
    color: '#EC4899',
    size: 14,
    speed: 0.00045,
    initialAngle: 0.3,
    cloudSupported: true,
    offlineSupported: true,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: true,
    bcp47: 'hi-IN',
    flagGlyph: 'HI',
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    script: 'Tamil',
    family: 'Dravidian',
    orbitRadius: 185,
    orbitIndex: 2,
    color: '#10B981',
    size: 13,
    speed: 0.00045,
    initialAngle: 1.5,
    cloudSupported: true,
    offlineSupported: true,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: true,
    bcp47: 'ta-IN',
    flagGlyph: 'TA',
  },
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    script: 'Kanji / Kana',
    family: 'Japonic',
    orbitRadius: 185,
    orbitIndex: 2,
    color: '#F43F5E',
    size: 14,
    speed: 0.00045,
    initialAngle: 2.8,
    cloudSupported: true,
    offlineSupported: true,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: true,
    bcp47: 'ja-JP',
    flagGlyph: 'JA',
  },
  {
    code: 'zh',
    name: 'Chinese (Simplified)',
    nativeName: '中文 (简体)',
    script: 'Simplified Han',
    family: 'Sino-Tibetan',
    orbitRadius: 185,
    orbitIndex: 2,
    color: '#EF4444',
    size: 15,
    speed: 0.00045,
    initialAngle: 4.2,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    limitations: 'Offline dictionary pack is currently in development. Cloud AI translation fully active.',
    popular: true,
    bcp47: 'zh-CN',
    flagGlyph: 'ZH',
  },
  {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    script: 'Arabic (RTL)',
    family: 'Afroasiatic (Semitic)',
    orbitRadius: 240,
    orbitIndex: 3,
    color: '#06B6D4',
    size: 14,
    speed: 0.0003,
    initialAngle: 0.2,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    limitations: 'Right-to-left script rendered natively. Offline lexicon pending pack release.',
    popular: true,
    bcp47: 'ar-SA',
    flagGlyph: 'AR',
  },
  {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    script: 'Hangul',
    family: 'Koreanic',
    orbitRadius: 240,
    orbitIndex: 3,
    color: '#8B5CF6',
    size: 13,
    speed: 0.0003,
    initialAngle: 1.4,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    limitations: 'High precision Korean cloud translation with honorific register awareness.',
    popular: true,
    bcp47: 'ko-KR',
    flagGlyph: 'KO',
  },
  {
    code: 'pt',
    name: 'Portuguese',
    nativeName: 'Português',
    script: 'Latin',
    family: 'Indo-European (Romance)',
    orbitRadius: 240,
    orbitIndex: 3,
    color: '#14B8A6',
    size: 13,
    speed: 0.0003,
    initialAngle: 2.6,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: true,
    bcp47: 'pt-BR',
    flagGlyph: 'PT',
  },
  {
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    script: 'Latin',
    family: 'Indo-European (Romance)',
    orbitRadius: 240,
    orbitIndex: 3,
    color: '#6366F1',
    size: 12,
    speed: 0.0003,
    initialAngle: 3.8,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: true,
    bcp47: 'it-IT',
    flagGlyph: 'IT',
  },
  {
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    script: 'Cyrillic',
    family: 'Indo-European (Slavic)',
    orbitRadius: 240,
    orbitIndex: 3,
    color: '#38BDF8',
    size: 13,
    speed: 0.0003,
    initialAngle: 5.0,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: true,
    bcp47: 'ru-RU',
    flagGlyph: 'RU',
  },
  {
    code: 'nl',
    name: 'Dutch',
    nativeName: 'Nederlands',
    script: 'Latin',
    family: 'Indo-European (Germanic)',
    orbitRadius: 300,
    orbitIndex: 4,
    color: '#FB923C',
    size: 12,
    speed: 0.0002,
    initialAngle: 0.6,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: false,
    bcp47: 'nl-NL',
    flagGlyph: 'NL',
  },
  {
    code: 'pl',
    name: 'Polish',
    nativeName: 'Polski',
    script: 'Latin',
    family: 'Indo-European (Slavic)',
    orbitRadius: 300,
    orbitIndex: 4,
    color: '#F472B6',
    size: 12,
    speed: 0.0002,
    initialAngle: 1.8,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: false,
    bcp47: 'pl-PL',
    flagGlyph: 'PL',
  },
  {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    script: 'Latin',
    family: 'Turkic',
    orbitRadius: 300,
    orbitIndex: 4,
    color: '#E11D48',
    size: 13,
    speed: 0.0002,
    initialAngle: 2.9,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: false,
    bcp47: 'tr-TR',
    flagGlyph: 'TR',
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    script: 'Latin with diacritics',
    family: 'Austroasiatic',
    orbitRadius: 300,
    orbitIndex: 4,
    color: '#84CC16',
    size: 12,
    speed: 0.0002,
    initialAngle: 4.1,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: false,
    bcp47: 'vi-VN',
    flagGlyph: 'VI',
  },
  {
    code: 'id',
    name: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    script: 'Latin',
    family: 'Austronesian',
    orbitRadius: 300,
    orbitIndex: 4,
    color: '#F97316',
    size: 12,
    speed: 0.0002,
    initialAngle: 5.3,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: false,
    bcp47: 'id-ID',
    flagGlyph: 'ID',
  },
  {
    code: 'fil',
    name: 'Filipino / Tagalog',
    nativeName: 'Wikang Filipino',
    script: 'Latin',
    family: 'Austronesian',
    orbitRadius: 350,
    orbitIndex: 4,
    color: '#0284C7',
    size: 12,
    speed: 0.00018,
    initialAngle: 0.9,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: false,
    ocrSupported: true,
    documentSupported: true,
    limitations: 'Web Speech STT browser support varies by OS. Text & OCR fully operational.',
    popular: false,
    bcp47: 'fil-PH',
    flagGlyph: 'FIL',
  },
  {
    code: 'th',
    name: 'Thai',
    nativeName: 'ไทย',
    script: 'Thai',
    family: 'Kra-Dai',
    orbitRadius: 350,
    orbitIndex: 4,
    color: '#A855F7',
    size: 12,
    speed: 0.00018,
    initialAngle: 2.2,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: false,
    ocrSupported: true,
    documentSupported: true,
    limitations: 'No word spaces in native script; segmented accurately via Cloud AI.',
    popular: false,
    bcp47: 'th-TH',
    flagGlyph: 'TH',
  },
  {
    code: 'el',
    name: 'Greek',
    nativeName: 'Ελληνικά',
    script: 'Greek',
    family: 'Indo-European (Hellenic)',
    orbitRadius: 350,
    orbitIndex: 4,
    color: '#0EA5E9',
    size: 12,
    speed: 0.00018,
    initialAngle: 3.5,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: false,
    bcp47: 'el-GR',
    flagGlyph: 'EL',
  },
  {
    code: 'sv',
    name: 'Swedish',
    nativeName: 'Svenska',
    script: 'Latin',
    family: 'Indo-European (North Germanic)',
    orbitRadius: 350,
    orbitIndex: 4,
    color: '#059669',
    size: 12,
    speed: 0.00018,
    initialAngle: 4.8,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: true,
    ocrSupported: true,
    documentSupported: true,
    popular: false,
    bcp47: 'sv-SE',
    flagGlyph: 'SV',
  },
  {
    code: 'sw',
    name: 'Swahili',
    nativeName: 'Kiswahili',
    script: 'Latin',
    family: 'Niger-Congo (Bantu)',
    orbitRadius: 350,
    orbitIndex: 4,
    color: '#D97706',
    size: 12,
    speed: 0.00018,
    initialAngle: 5.9,
    cloudSupported: true,
    offlineSupported: false,
    textSupported: true,
    speechSynthesisSupported: true,
    speechRecognitionSupported: false,
    ocrSupported: true,
    documentSupported: true,
    limitations: 'Speech recognition requires device support for sw-KE.',
    popular: false,
    bcp47: 'sw-KE',
    flagGlyph: 'SW',
  },
];

export function getLanguageByCode(code: string): LanguagePlanetData | undefined {
  return SUPPORTED_LANGUAGES.find((l) => l.code.toLowerCase() === code.toLowerCase());
}

export function searchLanguages(query: string, filter: 'ALL' | 'POPULAR' | 'OFFLINE' = 'ALL'): LanguagePlanetData[] {
  const cleanQ = query.trim().toLowerCase();
  return SUPPORTED_LANGUAGES.filter((lang) => {
    if (filter === 'POPULAR' && !lang.popular) return false;
    if (filter === 'OFFLINE' && !lang.offlineSupported) return false;
    if (!cleanQ) return true;
    return (
      lang.name.toLowerCase().includes(cleanQ) ||
      lang.nativeName.toLowerCase().includes(cleanQ) ||
      lang.code.toLowerCase().includes(cleanQ) ||
      lang.family.toLowerCase().includes(cleanQ)
    );
  });
}

/**
 * ISO 639-1 language universe catalog.
 * These entries are discoverable in the Solar System even when LingoFlow does
 * not currently expose translation/voice/OCR support for that language.
 */
export interface LanguageUniverseEntry {
  code: string;
  name: string;
  nativeName: string;
  alpha3?: string;
}

const ISO6391_UNIVERSE: Array<[string, string]> = [
  ['aa','Afar'],['ab','Abkhazian'],['ae','Avestan'],['af','Afrikaans'],['ak','Akan'],['am','Amharic'],['an','Aragonese'],['ar','Arabic'],['as','Assamese'],['av','Avaric'],['ay','Aymara'],['az','Azerbaijani'],
  ['ba','Bashkir'],['be','Belarusian'],['bg','Bulgarian'],['bh','Bihari languages'],['bi','Bislama'],['bm','Bambara'],['bn','Bengali'],['bo','Tibetan'],['br','Breton'],['bs','Bosnian'],
  ['ca','Catalan'],['ce','Chechen'],['ch','Chamorro'],['co','Corsican'],['cr','Cree'],['cs','Czech'],['cu','Church Slavic'],['cv','Chuvash'],['cy','Welsh'],
  ['da','Danish'],['de','German'],['dv','Divehi'],['dz','Dzongkha'],['ee','Ewe'],['el','Greek'],['en','English'],['eo','Esperanto'],['es','Spanish'],['et','Estonian'],['eu','Basque'],
  ['fa','Persian'],['ff','Fulah'],['fi','Finnish'],['fj','Fijian'],['fo','Faroese'],['fr','French'],['fy','Western Frisian'],['ga','Irish'],['gd','Scottish Gaelic'],['gl','Galician'],['gn','Guarani'],['gu','Gujarati'],
  ['gv','Manx'],['ha','Hausa'],['he','Hebrew'],['hi','Hindi'],['ho','Hiri Motu'],['hr','Croatian'],['ht','Haitian'],['hu','Hungarian'],['hy','Armenian'],['hz','Herero'],
  ['ia','Interlingua'],['id','Indonesian'],['ie','Interlingue'],['ig','Igbo'],['ii','Sichuan Yi'],['ik','Inupiaq'],['io','Ido'],['is','Icelandic'],['it','Italian'],['iu','Inuktitut'],
  ['ja','Japanese'],['jv','Javanese'],['ka','Georgian'],['kg','Kongo'],['ki','Kikuyu'],['kj','Kuanyama'],['kk','Kazakh'],['kl','Kalaallisut'],['km','Khmer'],['kn','Kannada'],['ko','Korean'],['kr','Kanuri'],['ks','Kashmiri'],['ku','Kurdish'],['kv','Komi'],['kw','Cornish'],['ky','Kyrgyz'],
  ['la','Latin'],['lb','Luxembourgish'],['lg','Ganda'],['li','Limburgan'],['ln','Lingala'],['lo','Lao'],['lt','Lithuanian'],['lu','Luba-Katanga'],['lv','Latvian'],
  ['mg','Malagasy'],['mh','Marshallese'],['mi','Maori'],['mk','Macedonian'],['ml','Malayalam'],['mn','Mongolian'],['mr','Marathi'],['ms','Malay'],['mt','Maltese'],['my','Burmese'],
  ['na','Nauru'],['nb','Norwegian Bokmal'],['nd','North Ndebele'],['ne','Nepali'],['ng','Ndonga'],['nl','Dutch'],['nn','Norwegian Nynorsk'],['no','Norwegian'],['nr','South Ndebele'],['nv','Navajo'],['ny','Chichewa'],
  ['oc','Occitan'],['oj','Ojibwa'],['om','Oromo'],['or','Odia'],['os','Ossetian'],['pa','Punjabi'],['pi','Pali'],['pl','Polish'],['ps','Pashto'],['pt','Portuguese'],['qu','Quechua'],['rm','Romansh'],['rn','Rundi'],['ro','Romanian'],['ru','Russian'],['rw','Kinyarwanda'],
  ['sa','Sanskrit'],['sc','Sardinian'],['sd','Sindhi'],['se','Northern Sami'],['sg','Sango'],['si','Sinhala'],['sk','Slovak'],['sl','Slovenian'],['sm','Samoan'],['sn','Shona'],['so','Somali'],['sq','Albanian'],['sr','Serbian'],['ss','Swati'],['st','Southern Sotho'],['su','Sundanese'],['sv','Swedish'],['sw','Swahili'],
  ['ta','Tamil'],['te','Telugu'],['tg','Tajik'],['th','Thai'],['ti','Tigrinya'],['tk','Turkmen'],['tl','Tagalog'],['tn','Tswana'],['to','Tonga'],['tr','Turkish'],['ts','Tsonga'],['tt','Tatar'],['tw','Twi'],['ty','Tahitian'],['ug','Uyghur'],['uk','Ukrainian'],['ur','Urdu'],['uz','Uzbek'],['ve','Venda'],['vi','Vietnamese'],['vo','Volapuk'],['wa','Walloon'],['wo','Wolof'],['xh','Xhosa'],['yi','Yiddish'],['yo','Yoruba'],['za','Zhuang'],['zh','Chinese'],['zu','Zulu']
];

export const WORLD_LANGUAGE_UNIVERSE: LanguagePlanetData[] = ISO6391_UNIVERSE.map(([code, name], index) => {
  const supported = SUPPORTED_LANGUAGES.find((language) => language.code === code);
  if (supported) return supported;
  const orbitIndex = (index % 10) + 1;
  const palette = ['#6670ff','#22d3ee','#a78bfa','#34d399','#f59e0b','#fb7185','#38bdf8','#c084fc'];
  return {
    code,
    name,
    nativeName: name,
    script: 'Language catalog',
    family: 'World language',
    orbitRadius: 150 + (orbitIndex - 1) * 48,
    orbitIndex,
    color: palette[index % palette.length],
    size: 5.5,
    speed: 0.000035 + (index % 7) * 0.000004,
    initialAngle: (index * 2.399963) % (Math.PI * 2),
    cloudSupported: false,
    offlineSupported: false,
    textSupported: false,
    speechSynthesisSupported: false,
    speechRecognitionSupported: false,
    ocrSupported: false,
    documentSupported: false,
    limitations: 'Explore-only catalog entry. Translation support is not currently enabled in LingoFlow.',
    popular: false,
    bcp47: code,
    flagGlyph: code.toUpperCase(),
  };
});
